
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfznotihbhltlxsbnsry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmem5vdGloYmhsdGx4c2Juc3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTc5MTksImV4cCI6MjA1NDY3MzkxOX0.Lztf5W-ZxCOR9pueSq-AEh4h7V0iiHkubsASEuAjMxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
