// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syqfbzdepvnjybfpruao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cWZiemRlcHZuanliZnBydWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDY1MjAsImV4cCI6MjA1MzkyMjUyMH0._zj8RxorcvMdWz6S7ox_tHWSsgYxbR3gbvmOO97f3Kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);